In [92]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [93]:
import pandas as pd
import numpy as np

In [94]:
data_path = '/content/drive/MyDrive/data/'

In [95]:
train_tita = pd.read_csv(f'{data_path}titanic_train.csv')
test_tita = pd.read_csv(f'{data_path}titanic_test.csv')

In [96]:
train_tita.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 916 entries, 0 to 915
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   passengerid  916 non-null    int64  
 1   survived     916 non-null    int64  
 2   pclass       916 non-null    int64  
 3   name         916 non-null    object 
 4   gender       916 non-null    object 
 5   age          736 non-null    float64
 6   sibsp        916 non-null    int64  
 7   parch        916 non-null    int64  
 8   ticket       916 non-null    object 
 9   fare         916 non-null    float64
 10  cabin        210 non-null    object 
 11  embarked     916 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 86.0+ KB


In [97]:
train_tita.isnull().sum()

passengerid      0
survived         0
pclass           0
name             0
gender           0
age            180
sibsp            0
parch            0
ticket           0
fare             0
cabin          706
embarked         0
dtype: int64

In [98]:
test_tita.isnull().sum()

passengerid      0
pclass           0
name             0
gender           0
age             83
sibsp            0
parch            0
ticket           0
fare             1
cabin          308
embarked         2
dtype: int64

In [99]:
train_tita_cp = train_tita.copy()
test_tita_cp = test_tita.copy()

In [100]:
train_tita_cp.shape, test_tita_cp.shape

((916, 12), (393, 11))

In [101]:
train_tita_cp.head()

passengerid  survived  pclass                      name  ...    ticket     fare  cabin  embarked
0          494         0       1   Artagaveytia, Mr. Ramon  ...  PC 17609  49.5042    NaN         C
1          462         0       3       Morley, Mr. William  ...    364506   8.0500    NaN         S
2         1286         0       3  Kink-Heilmann, Mr. Anton  ...    315153  22.0250    NaN         S
3         1130         1       2     Hiltunen, Miss. Marta  ...    250650  13.0000    NaN         S
4          461         1       1       Anderson, Mr. Harry  ...     19952  26.5500    E12         S

[5 rows x 12 columns]

In [102]:
target = train_tita_cp.pop('survived')
target

0      0
1      0
2      0
3      1
4      1
      ..
911    1
912    0
913    0
914    0
915    0
Name: survived, Length: 916, dtype: int64

In [103]:
train_tita_cp.isnull().sum()

passengerid      0
pclass           0
name             0
gender           0
age            180
sibsp            0
parch            0
ticket           0
fare             0
cabin          706
embarked         0
dtype: int64

In [104]:
test_tita_cp.isnull().sum()

passengerid      0
pclass           0
name             0
gender           0
age             83
sibsp            0
parch            0
ticket           0
fare             1
cabin          308
embarked         2
dtype: int64

In [105]:
# cols = train_tita_cp.select_dtypes('object').columns
cols = train_tita_cp.columns
cols

Index(['passengerid', 'pclass', 'name', 'gender', 'age', 'sibsp', 'parch',
       'ticket', 'fare', 'cabin', 'embarked'],
      dtype='object')

In [106]:
train_tita_ft = train_tita_cp[cols]
test_tita_ft = test_tita_cp[cols]

In [107]:
age_mean = train_tita_ft['age'].mean()
fare_median = train_tita_ft['fare'].median()
cabin_mode = train_tita_ft['cabin'].mode()[0]
embarked_mode = train_tita_ft['embarked'].mode()[0]

In [108]:
age_mean, fare_median, cabin_mode, embarked_mode

(29.904891304347824, 14.5, 'B57 B59 B63 B66', 'S')

In [109]:
train_tita_ft['age'] = train_tita_ft['age'].fillna(age_mean)
train_tita_ft['fare'] = train_tita_ft['fare'].fillna(fare_median)
train_tita_ft['cabin'] = train_tita_ft['cabin'].fillna(cabin_mode)
train_tita_ft['embarked'] = train_tita_ft['embarked'].fillna(embarked_mode)

In [110]:
test_tita_ft['age'] = test_tita_ft['age'].fillna(age_mean)
test_tita_ft['fare'] = test_tita_ft['fare'].fillna(fare_median)
test_tita_ft['cabin'] = test_tita_ft['cabin'].fillna(cabin_mode)
test_tita_ft['embarked'] = test_tita_ft['embarked'].fillna(embarked_mode)

In [111]:
train_tita_ft.isnull().sum().sum(), test_tita_ft.isnull().sum().sum()

(0, 0)

In [112]:
train_tita_ft.head()

passengerid  pclass                      name  ...     fare            cabin  embarked
0          494       1   Artagaveytia, Mr. Ramon  ...  49.5042  B57 B59 B63 B66         C
1          462       3       Morley, Mr. William  ...   8.0500  B57 B59 B63 B66         S
2         1286       3  Kink-Heilmann, Mr. Anton  ...  22.0250  B57 B59 B63 B66         S
3         1130       2     Hiltunen, Miss. Marta  ...  13.0000  B57 B59 B63 B66         S
4          461       1       Anderson, Mr. Harry  ...  26.5500              E12         S

[5 rows x 11 columns]

In [113]:
test_tita_ft.head()

passengerid  pclass                       name  ...     fare            cabin  embarked
0          253       1  Stead, Mr. William Thomas  ...  26.5500              C87         S
1           84       1    Carrau, Mr. Francisco M  ...  47.1000  B57 B59 B63 B66         S
2          771       3     Lievens, Mr. Rene Aime  ...   9.5000  B57 B59 B63 B66         S
3         1052       3         Smyth, Miss. Julia  ...   7.7333  B57 B59 B63 B66         Q
4         1005       3   Buckley, Miss. Katherine  ...   7.2833  B57 B59 B63 B66         Q

[5 rows x 11 columns]

In [114]:
cols = train_tita_ft.select_dtypes('object').columns
cols

Index(['name', 'gender', 'ticket', 'cabin', 'embarked'], dtype='object')

In [115]:
train_tita_ft[cols]

name  gender      ticket            cabin embarked
0         Artagaveytia, Mr. Ramon    male    PC 17609  B57 B59 B63 B66        C
1             Morley, Mr. William    male      364506  B57 B59 B63 B66        S
2        Kink-Heilmann, Mr. Anton    male      315153  B57 B59 B63 B66        S
3           Hiltunen, Miss. Marta  female      250650  B57 B59 B63 B66        S
4             Anderson, Mr. Harry    male       19952              E12        S
..                            ...     ...         ...              ...      ...
911        Lesurer, Mr. Gustave J    male    PC 17755             B101        C
912             Ryan, Mr. Patrick    male      371110  B57 B59 B63 B66        Q
913              Coleff, Mr. Peju    male      349210  B57 B59 B63 B66        S
914               Rekic, Mr. Tido    male      349249  B57 B59 B63 B66        S
915  Nicholls, Mr. Joseph Charles    male  C.A. 33112  B57 B59 B63 B66        S

[916 rows x 5 columns]

In [116]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown= 'ignore')

In [117]:
enc.fit(train_tita_ft[cols])

OneHotEncoder(handle_unknown='ignore')

In [118]:
enc.transform(train_tita_ft[cols]).toarray()

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [119]:
enc.get_feature_names_out()

array(['name_Abbott, Master. Eugene Joseph',
       'name_Abbott, Mr. Rossmore Edward',
       'name_Abbott, Mrs. Stanton (Rosa Hunt)', ..., 'embarked_C',
       'embarked_Q', 'embarked_S'], dtype=object)

In [120]:
tmp = pd.DataFrame(
    enc.transform(train_tita_ft[cols]).toarray(),
    columns = enc.get_feature_names_out()
)

train_tita_ft = pd.concat([train_tita_ft, tmp], axis = 1).drop(columns = cols)
train_tita_ft

passengerid  pclass        age  sibsp  ...  cabin_T  embarked_C  embarked_Q  embarked_S
0            494       1  71.000000      0  ...      0.0         1.0         0.0         0.0
1            462       3  34.000000      0  ...      0.0         0.0         0.0         1.0
2           1286       3  29.000000      3  ...      0.0         0.0         0.0         1.0
3           1130       2  18.000000      1  ...      0.0         0.0         0.0         1.0
4            461       1  48.000000      0  ...      0.0         0.0         0.0         1.0
..           ...     ...        ...    ...  ...      ...         ...         ...         ...
911          738       1  35.000000      0  ...      0.0         1.0         0.0         0.0
912          518       3  29.904891      0  ...      0.0         0.0         1.0         0.0
913          664       3  36.000000      0  ...      0.0         0.0         0.0         1.0
914          109       3  38.000000      0  ...      0.0         0.0         0.0         1.0
915          146       2  19.000000      1  ...      0.0         0.0         0.0         1.0

[916 rows x 1762 columns]

In [121]:
tmp = pd.DataFrame(
    enc.transform(test_tita_ft[cols]).toarray(),
    columns = enc.get_feature_names_out()
)

test_tita_ft = pd.concat([test_tita_ft, tmp], axis = 1).drop(columns = cols)
test_tita_ft

passengerid  pclass        age  sibsp  ...  cabin_T  embarked_C  embarked_Q  embarked_S
0            253       1  62.000000      0  ...      0.0         0.0         0.0         1.0
1             84       1  28.000000      0  ...      0.0         0.0         0.0         1.0
2            771       3  24.000000      0  ...      0.0         0.0         0.0         1.0
3           1052       3  29.904891      0  ...      0.0         0.0         1.0         0.0
4           1005       3  18.500000      0  ...      0.0         0.0         1.0         0.0
..           ...     ...        ...    ...  ...      ...         ...         ...         ...
388          567       3  19.000000      0  ...      0.0         0.0         0.0         1.0
389          831       3  15.000000      1  ...      0.0         1.0         0.0         0.0
390          116       3  21.000000      0  ...      0.0         0.0         0.0         1.0
391          902       3  29.904891      0  ...      0.0         0.0         0.0         1.0
392          322       3  27.000000      0  ...      0.0         0.0         0.0         1.0

[393 rows x 1762 columns]

In [122]:
train_tita_ft.shape, test_tita_ft.shape

((916, 1762), (393, 1762))

In [123]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [124]:
train_tita_ft.columns

Index(['passengerid', 'pclass', 'age', 'sibsp', 'parch', 'fare',
       'name_Abbott, Master. Eugene Joseph',
       'name_Abbott, Mr. Rossmore Edward',
       'name_Abbott, Mrs. Stanton (Rosa Hunt)',
       'name_Abelseth, Miss. Karen Marie',
       ...
       'cabin_F G63', 'cabin_F G73', 'cabin_F2', 'cabin_F33', 'cabin_F4',
       'cabin_G6', 'cabin_T', 'embarked_C', 'embarked_Q', 'embarked_S'],
      dtype='object', length=1762)

In [125]:
train_tita_ft[train_tita_ft.columns]= scaler.fit_transform(train_tita_ft)
train_tita_ft

passengerid  pclass       age  sibsp  ...  cabin_T  embarked_C  embarked_Q  embarked_S
0       0.376911     0.0  0.887260  0.000  ...      0.0         1.0         0.0         0.0
1       0.352446     1.0  0.423776  0.000  ...      0.0         0.0         0.0         1.0
2       0.982416     1.0  0.361142  0.375  ...      0.0         0.0         0.0         1.0
3       0.863150     0.5  0.223350  0.125  ...      0.0         0.0         0.0         1.0
4       0.351682     0.0  0.599148  0.000  ...      0.0         0.0         0.0         1.0
..           ...     ...       ...    ...  ...      ...         ...         ...         ...
911     0.563456     0.0  0.436302  0.000  ...      0.0         1.0         0.0         0.0
912     0.395260     1.0  0.372478  0.000  ...      0.0         0.0         1.0         0.0
913     0.506881     1.0  0.448829  0.000  ...      0.0         0.0         0.0         1.0
914     0.082569     1.0  0.473882  0.000  ...      0.0         0.0         0.0         1.0
915     0.110856     0.5  0.235876  0.125  ...      0.0         0.0         0.0         1.0

[916 rows x 1762 columns]

In [126]:
test_tita_ft[test_tita_ft.columns]= scaler.transform(test_tita_ft)
test_tita_ft

passengerid  pclass       age  sibsp  ...  cabin_T  embarked_C  embarked_Q  embarked_S
0       0.192661     0.0  0.774521  0.000  ...      0.0         0.0         0.0         1.0
1       0.063456     0.0  0.348616  0.000  ...      0.0         0.0         0.0         1.0
2       0.588685     1.0  0.298509  0.000  ...      0.0         0.0         0.0         1.0
3       0.803517     1.0  0.372478  0.000  ...      0.0         0.0         1.0         0.0
4       0.767584     1.0  0.229613  0.000  ...      0.0         0.0         1.0         0.0
..           ...     ...       ...    ...  ...      ...         ...         ...         ...
388     0.432722     1.0  0.235876  0.000  ...      0.0         0.0         0.0         1.0
389     0.634557     1.0  0.185770  0.125  ...      0.0         1.0         0.0         0.0
390     0.087920     1.0  0.260929  0.000  ...      0.0         0.0         0.0         1.0
391     0.688838     1.0  0.372478  0.000  ...      0.0         0.0         0.0         1.0
392     0.245413     1.0  0.336089  0.000  ...      0.0         0.0         0.0         1.0

[393 rows x 1762 columns]

In [127]:
from sklearn.model_selection import train_test_split
x_train, x_valid, y_train, y_valid = train_test_split(train_tita_ft, target, random_state = 42, test_size = 0.2)

In [128]:
x_train.shape, x_valid.shape, y_train.shape, y_valid.shape

((732, 1762), (184, 1762), (732,), (184,))

In [129]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 42)

In [130]:
model.fit(x_train, y_train)

LogisticRegression(random_state=42)

In [131]:
pred = model.predict(x_valid)
pred

array([0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1])

In [132]:
from sklearn.metrics import accuracy_score
accuracy_score(y_valid, pred)

0.8315217391304348

In [133]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

In [134]:
cv = KFold(n_splits = 5, shuffle = True, random_state = 42)

In [135]:
scores = cross_val_score(model, train_tita_ft, target, scoring = 'roc_auc', cv = cv, n_jobs = -1)
scores

array([0.91065163, 0.96342673, 0.90152311, 0.88428431, 0.90482538])

In [136]:
scores.mean()

0.9129422313199894

In [137]:
model.fit(train_tita_ft, target)

LogisticRegression(random_state=42)

In [138]:
pred = model.predict(test_tita_ft, )
pred

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,

In [139]:
pd.DataFrame(pred, columns = ['target']).to_csv('로지원핫크밸.csv', index = False)