# 텐서 만들기

## tensor함수
- 입력 받은 데이터의 데이터 타입을 유지하면서 텐서로 변경(default = int64)

- 주요 파라미터
  - dtype
    - 데이터 타입을 지정
    - 기본값 : None, 입력받은 데이터 타입을 유지

  - device
    - 텐서가 위치할 장치 지정 → 보통 to를 사용

 - 리스트 > 텐서

In [4]:
import torch
import numpy as np

In [8]:
data = [
    [1,2,3],
    [4,5,6]
]

x = torch.tensor(data) # 데이터타입 그대로 반영
x

tensor([[1, 2, 3],
        [4, 5, 6]])

# 텐서 주요 속성

## 텐서 차원수

In [6]:
x.ndim

2

## 데이터 타입 확인

In [9]:
x.dtype

torch.int64

## ndarray텐서로 변환

In [10]:
data = np.array(data)
data

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
display(type(data))
torch.tensor(data)

numpy.ndarray

tensor([[1, 2, 3],
        [4, 5, 6]])

## 장치 지정 확인

In [13]:
x.device # gpu 전환 시 'gpu' 출력

device(type='cpu')

## tensor의 데이터 타입 > 원하는 타입으로 전환

In [14]:
torch.tensor(data, dtype = torch.float64)
# torch.tensor(data, dtype = torch.int32)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

## 신경망 모델에 텐서를 전달할 때

- 정수형 : int64
- 실수형 : float32

## Tensor 클래스
- 입력받은 데이터를 텐서로 변경
- 데이터타입을 float32형태로 변경

In [15]:
data.dtype # 기존 데이터타입

dtype('int64')

In [16]:
x = torch.Tensor(data) #Tensor함수이므로 데이터타입 변경
x.dtype

torch.float32

## from_numpy 함수

- ndarray를 텐서로 변환
- data가 numpy일 떄, torch.tensor(data) 대신 사용

In [17]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
x = torch.from_numpy(data)
display(x)
x.dtype

tensor([[1, 2, 3],
        [4, 5, 6]])

torch.int64

- 텐서 변경 시 numpy에 영향 미치는 경우

In [20]:
x[0,0] = 100
x

tensor([[100,   2,   3],
        [  4,   5,   6]])

In [21]:
data

array([[100,   2,   3],
       [  4,   5,   6]])

## 텐서 > ndarray 변환

In [22]:
x.numpy()

array([[100,   2,   3],
       [  4,   5,   6]])

In [23]:
np.array(x)

array([[100,   2,   3],
       [  4,   5,   6]])

## 텐서 > 파이썬 자료형 변환

- 리스트

In [24]:
x.tolist()

[[100, 2, 3], [4, 5, 6]]

- 스칼라 텐서 > 파이썬 자료형 변환

In [25]:
a = torch.tensor(1004)
a

tensor(1004)

In [26]:
a.item()

1004

# 인덱싱,슬라이싱,마스킹,멀티인덱싱

In [28]:
data = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

x = torch.Tensor(data)
display(x)
x.dtype

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

torch.float32

In [30]:
x[2, 0], x[0,2]

(tensor(7.), tensor(3.))

In [32]:
mask = [False, False, True]
x[:,mask]

tensor([[3.],
        [6.],
        [9.]])

In [33]:
# 멀티 인덱싱
idx_list = [0,2]
x[idx_list]

tensor([[1., 2., 3.],
        [7., 8., 9.]])

# 랜덤한 값을 가지는 텐서 생성

- rand 함수
  - 0~1 사이의 랜덤값 생성, 음수값x

- randn 함수
  - 평균: 0, 분산: 1인 정규분포 랜덤한 값 생성(표준정규분포), 음수값o

- randint 함수
  - 지정한 범위 내의 정수를 랜덤하게 생성, 음수값o

- 시드 고정
  - torch.manual_seed(42)

- _like(객체)
  - 입력데이터의 shape에 맞춰 0~1에 값을 생성

In [34]:
torch.manual_seed(42)
torch.rand(5)

tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904])

In [37]:
# 3차원 형태
torch.rand([5,2,3])

tensor([[[0.3958, 0.9147, 0.2036],
         [0.2018, 0.2018, 0.9497]],

        [[0.6666, 0.9811, 0.0874],
         [0.0041, 0.1088, 0.1637]],

        [[0.7025, 0.6790, 0.9155],
         [0.2418, 0.1591, 0.7653]],

        [[0.2979, 0.8035, 0.3813],
         [0.7860, 0.1115, 0.2477]],

        [[0.6524, 0.6057, 0.3725],
         [0.7980, 0.8399, 0.1374]]])

In [38]:
x.shape

torch.Size([3, 3])

In [43]:
torch.rand_like(x)

tensor([[0.4654, 0.1612, 0.1568],
        [0.2083, 0.3289, 0.1054],
        [0.9192, 0.4008, 0.9302]])

In [41]:
torch.randn(5)

tensor([ 1.1351,  0.7592, -3.5945,  0.0192,  0.1052])

In [44]:
# 2차원 형태
torch.rand([2,3])

tensor([[0.6558, 0.0766, 0.8460],
        [0.3624, 0.3083, 0.0850]])

In [45]:
torch.randn_like(x)

tensor([[ 0.9603,  0.5139,  0.0760],
        [-0.0740, -0.3555,  0.3692],
        [-0.6200,  0.3825, -0.7136]])

In [48]:
torch.randint(1,11, [3,4])

tensor([[7, 9, 3, 9],
        [3, 2, 1, 1],
        [7, 6, 1, 7]])

In [49]:
torch.randint(-11,11, [3,4])

tensor([[  0,   5,   5,   9],
        [ -3,   9,   6,   6],
        [-10,   9,   3,   1]])

In [52]:
torch.randint_like(x, 1, 21)

tensor([[11., 19., 19.],
        [10., 12., 14.],
        [ 2.,  5.,  2.]])

# 정한 값을 가지는 텐서 생성

In [53]:
torch.arange(1,11,2)

tensor([1, 3, 5, 7, 9])

In [54]:
torch.ones(10)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [55]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [56]:
torch.ones(3,2,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [57]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [58]:
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [59]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [60]:
torch.zeros(5,2,3)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [61]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [63]:
torch.zeros([3,4,5], dtype = torch.int32)

tensor([[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]], dtype=torch.int32)

In [65]:
torch.zeros(3,4,5, dtype = torch.float64)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=torch.float64)

In [66]:
torch.full([2,3], True)

tensor([[True, True, True],
        [True, True, True]])

In [67]:
torch.full_like(x, 111)

tensor([[111., 111., 111.],
        [111., 111., 111.],
        [111., 111., 111.]])

# GPU, CPU장치 이동

In [69]:
torch.cuda.is_available() # gpu(cuda) 연결 안되어 있을 경우

False

In [70]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [71]:
x.to(device) # cpu

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

# 텐서 연산하기

In [72]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

- 제곱

In [73]:
# x * x
torch.mul(x,x)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

- 뺄셈

In [74]:
# x - x
torch.sub(x,x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

- 덧셈

In [75]:
# x + x
torch.add(x,x)

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.],
        [14., 16., 18.]])

- 나눗셈

In [76]:
# x / x
torch.div(x,x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

- 브로드캐스팅 지원

In [77]:
x ** 2

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [85]:
x * 2

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.],
        [14., 16., 18.]])

- 행렬곱

In [78]:
y = torch.Tensor([
    [1,2],
    [3,4],
    [5,6]
])
y.shape

torch.Size([3, 2])

In [81]:
y.dtype

torch.float32

In [79]:
torch.matmul(x,y)


tensor([[ 22.,  28.],
        [ 49.,  64.],
        [ 76., 100.]])

In [80]:
 x @ y

tensor([[ 22.,  28.],
        [ 49.,  64.],
        [ 76., 100.]])

In [83]:
x1 = torch.randint(1,21, [2,3,4])
x2 = torch.randint(1,21, [2,4,5])
x1.shape, x2.shape

(torch.Size([2, 3, 4]), torch.Size([2, 4, 5]))

In [87]:
display(torch.matmul(x1,x2)) # 행렬곱 3행5열
torch.matmul(x1,x2).shape

tensor([[[ 283,  431,  447,  278,  386],
         [ 428,  433,  364,  158,  363],
         [ 491,  678,  435,  204,  421]],

        [[ 600,  587,  342,  351,  431],
         [ 483,  861,  576,  454,  607],
         [ 665, 1013,  550,  606,  893]]])

torch.Size([2, 3, 5])

# 집계하기

In [88]:
data = [
    [1,2,3],
    [4,5,6]
]

x = torch.Tensor(data)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [90]:
x.dtype

torch.float32

In [89]:
torch.mean(x)

tensor(3.5000)

In [91]:
torch.sum(x)

tensor(21.)

In [92]:
# axis = 0
x.sum(dim = 0)

tensor([5., 7., 9.])

In [93]:
# axis = 1
x.sum(dim = 1)

tensor([ 6., 15.])

# 텐서 차원 변경

- view 메서드
  - 원소의 순서를 유지하면서 차원을 변경
  - 원본 텐서와 메모리 공유하기 때문에, 반환된 텐서의 데이터를 변경하면 원본 텐서도 변경됨

- reshape 메서드
  - view와 실행 결과는 동일
  - view와 달리 메모리 공간상에서 연속적이지 않은 경우에도 변환 가능
  - view 불가할 때 사용, 메모리 공간상에서 요소들이 인접해 있지 않은 경우는 copy해서 반환

In [95]:
x.shape

torch.Size([2, 3])

In [96]:
x_view = x.view(3,2)
x_view

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [97]:
x_view[2,1] = 100
x_view

tensor([[  1.,   2.],
        [  3.,   4.],
        [  5., 100.]])

In [98]:
# 원본 텐서 변경됨
x

tensor([[  1.,   2.,   3.],
        [  4.,   5., 100.]])

In [111]:
data = [
    [1,2,3],
    [4,5,6]
]

x = torch.Tensor(data)

x_reshape = x.reshape(-1) # 1차원 형태 변경 > reshape(-1)
x_reshape, x_reshape.shape

(tensor([1., 2., 3., 4., 5., 6.]), torch.Size([6]))

In [112]:
x_reshape = x.reshape([6,1])
x_reshape, x_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.]]),
 torch.Size([6, 1]))

In [113]:
x_reshape[0,0] = 1000
x_reshape, x_reshape.shape

(tensor([[1000.],
         [   2.],
         [   3.],
         [   4.],
         [   5.],
         [   6.]]),
 torch.Size([6, 1]))

## transpose 메서드
- 차원 맞바꾸기
- 두 개의 차원만 가능
- torch.transpose(input, dim0, dim1)
  - input: 차원을 교환할 입력 텐서
  - dim0: 교환할 첫 번째 차원의 인덱스
  - dim1: 교환할 두 번째 차원의 인덱스

In [114]:
x

tensor([[1000.,    2.,    3.],
        [   4.,    5.,    6.]])

In [126]:
x.transpose(0,1)

tensor([[1000.,    4.],
        [   2.,    5.],
        [   3.,    6.]])

In [130]:
x = torch.rand(2, 3, 4)
display(x)
x.shape

tensor([[[0.3769, 0.0472, 0.0299, 0.2610],
         [0.2458, 0.6558, 0.3544, 0.3044],
         [0.9767, 0.6742, 0.8565, 0.2579]],

        [[0.2958, 0.6838, 0.1669, 0.1731],
         [0.4759, 0.3171, 0.1252, 0.7966],
         [0.9021, 0.5811, 0.4129, 0.0369]]])

torch.Size([2, 3, 4])

In [135]:
y = torch.transpose(x, 0, 1)
display(y)
y.shape

tensor([[[0.3769, 0.0472, 0.0299, 0.2610],
         [0.2958, 0.6838, 0.1669, 0.1731]],

        [[0.2458, 0.6558, 0.3544, 0.3044],
         [0.4759, 0.3171, 0.1252, 0.7966]],

        [[0.9767, 0.6742, 0.8565, 0.2579],
         [0.9021, 0.5811, 0.4129, 0.0369]]])

torch.Size([3, 2, 4])

## permute 메서드

- 여러 개 차원 맞바꾸기
- ex) shape(a,b,c) > shape(b,a,c)

In [137]:
# 3차원 3개 샘플, 4
x = torch.arange(1,25).view(2,3,4)
x

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [138]:
display(x.permute(1,0,2))
x.permute(1,0,2).shape

tensor([[[ 1,  2,  3,  4],
         [13, 14, 15, 16]],

        [[ 5,  6,  7,  8],
         [17, 18, 19, 20]],

        [[ 9, 10, 11, 12],
         [21, 22, 23, 24]]])

torch.Size([3, 2, 4])

## unsqueeze 메서드
- 차원의 크기1인 차원을 생성하는 메서드 > 벡터
- 몇 번째 차원에 크기가 1인 차원을 생성할지 지정

In [139]:
x = torch.arange(1,7)
x

tensor([1, 2, 3, 4, 5, 6])

In [143]:
display(x.unsqueeze(1))
x.unsqueeze(1).shape

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

torch.Size([6, 1])

In [144]:
x.view(-1,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

## squeeze 메서드
- 차원의 크기가 1인 차원 제거
- 차원을 설정하지 않으면

In [147]:
x = torch.rand([1,3,1,20,1])
# display(x)
x.shape

torch.Size([1, 3, 1, 20, 1])

In [149]:
x.squeeze().shape # 전체에서 제거

torch.Size([3, 20])

In [150]:
x.squeeze(4).shape # 4번째 차원의 크기 =1일 경우, 삭제

torch.Size([1, 3, 1, 20])

# 텐서 합치기

In [153]:
x1 = torch.ones(2,3)
x2 = torch.zeros(2,3)
x1.shape, x2.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [154]:
x1

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [155]:
x2

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [152]:
display(torch.cat([x1,x2], dim = 0))
torch.cat([x1,x2], dim = 0).shape

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])

torch.Size([4, 3])

In [156]:
display(torch.cat([x1,x2], dim = 1))
torch.cat([x1,x2], dim = 1).shape

tensor([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]])

torch.Size([2, 6])